version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - JWT_KEY=oW_FL9WS8RxDbuCRz47i9S0Ilvg-zK2NxmjhKkwqFH4

