# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], default=None, max_length=4, null=True)),
                ('chapter', models.IntegerField(default=None, null=True)),
                ('language_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adverb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], default=None, max_length=4, null=True)),
                ('chapter', models.IntegerField(default=None, null=True)),
                ('language_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correct', models.BooleanField(default=False)),
                ('mode', models.CharField(default='', max_length=32)),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('correction', models.BooleanField(default=False)),
                ('correct_answer', models.CharField(default='', max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], default=None, max_length=4, null=True)),
                ('chapter', models.IntegerField(default=None, null=True)),
                ('language_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singular_form', models.CharField(max_length=128)),
                ('plural_form', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], default=None, max_length=4, null=True)),
                ('chapter', models.IntegerField(default=None, null=True)),
                ('language_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], default=None, max_length=4, null=True)),
                ('chapter', models.IntegerField(default=None, null=True)),
                ('language_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], default=None, max_length=4, null=True)),
                ('chapter', models.IntegerField(default=None, null=True)),
                ('language_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation', models.CharField(max_length=512)),
                ('form', models.CharField(choices=[('s', 'singular'), ('p', 'plural')], max_length=1)),
                ('language_code', models.CharField(default='en_US', max_length=5)),
                ('noun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Noun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], default=None, max_length=4, null=True)),
                ('chapter', models.IntegerField(default=None, null=True)),
                ('language_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='translation',
            name='verb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Verb'),
        ),
        migrations.AddField(
            model_name='answer',
            name='noun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Noun'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='verb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Verb'),
        ),
    ]
