# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 01:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('object_type', models.CharField(max_length=32)),
                ('correct', models.BooleanField(default=False)),
                ('mode', models.CharField(default='', max_length=16)),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('correction', models.BooleanField(default=False)),
                ('correct_answer', models.CharField(default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singular_form', models.CharField(max_length=128)),
                ('plural_form', models.CharField(max_length=128)),
                ('language_code', models.CharField(max_length=5)),
                ('gender', models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NounTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128)),
                ('form', models.CharField(choices=[('s', 'singular'), ('p', 'plural')], max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(default='en_US', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('noun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Noun')),
            ],
        ),
    ]
