# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noun',
            name='level',
            field=models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], default=None, max_length=3, null=True),
        ),
    ]
