# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='object_type',
        ),
        migrations.AddField(
            model_name='answer',
            name='noun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Noun'),
        ),
    ]
