# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='auxiliary',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='verb',
            name='irregular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='past_participle',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='verb',
            name='seperable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='type',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='verb',
            name='verb',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='noun',
            name='plural_form',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='noun',
            name='singular_form',
            field=models.CharField(max_length=64),
        ),
    ]
