# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171126_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjective',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None),
        ),
        migrations.AddField(
            model_name='adverb',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None),
        ),
        migrations.AddField(
            model_name='noun',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None),
        ),
        migrations.AddField(
            model_name='phrase',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None),
        ),
        migrations.AddField(
            model_name='preposition',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None),
        ),
        migrations.AddField(
            model_name='pronoun',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None),
        ),
        migrations.AddField(
            model_name='verb',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='adjective',
            name='level',
            field=models.CharField(choices=[('a1.1', 'a1.1'), ('a1.2', 'a1.2'), ('a2.1', 'a2.1'), ('a2.2', 'a2.2'), ('b1.1', 'b1.2'), ('b2.1', 'b2.2'), ('c1', 'c1')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='adverb',
            name='level',
            field=models.CharField(choices=[('a1.1', 'a1.1'), ('a1.2', 'a1.2'), ('a2.1', 'a2.1'), ('a2.2', 'a2.2'), ('b1.1', 'b1.2'), ('b2.1', 'b2.2'), ('c1', 'c1')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='noun',
            name='level',
            field=models.CharField(choices=[('a1.1', 'a1.1'), ('a1.2', 'a1.2'), ('a2.1', 'a2.1'), ('a2.2', 'a2.2'), ('b1.1', 'b1.2'), ('b2.1', 'b2.2'), ('c1', 'c1')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='level',
            field=models.CharField(choices=[('a1.1', 'a1.1'), ('a1.2', 'a1.2'), ('a2.1', 'a2.1'), ('a2.2', 'a2.2'), ('b1.1', 'b1.2'), ('b2.1', 'b2.2'), ('c1', 'c1')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='preposition',
            name='level',
            field=models.CharField(choices=[('a1.1', 'a1.1'), ('a1.2', 'a1.2'), ('a2.1', 'a2.1'), ('a2.2', 'a2.2'), ('b1.1', 'b1.2'), ('b2.1', 'b2.2'), ('c1', 'c1')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pronoun',
            name='level',
            field=models.CharField(choices=[('a1.1', 'a1.1'), ('a1.2', 'a1.2'), ('a2.1', 'a2.1'), ('a2.2', 'a2.2'), ('b1.1', 'b1.2'), ('b2.1', 'b2.2'), ('c1', 'c1')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='level',
            field=models.CharField(choices=[('a1.1', 'a1.1'), ('a1.2', 'a1.2'), ('a2.1', 'a2.1'), ('a2.2', 'a2.2'), ('b1.1', 'b1.2'), ('b2.1', 'b2.2'), ('c1', 'c1')], default=None, max_length=4, null=True),
        ),
    ]
