# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171128_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjective',
            name='adjective',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='answer',
            name='adjective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Adjective'),
        ),
        migrations.AddField(
            model_name='translation',
            name='adjective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Adjective'),
        ),
    ]
