# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171125_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='nountranslation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nountranslation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='noun',
            name='chapter',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='noun',
            name='level',
            field=models.CharField(choices=[('m', 'masculine'), ('f', 'feminine'), ('n', 'neuter')], default=None, max_length=2, null=True),
        ),
    ]
