# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='mode',
            field=models.CharField(default='', max_length=16),
        ),
    ]
