# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171128_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjective',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='adverb',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='noun',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='preposition',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='pronoun',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='verb',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
    ]
