# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171126_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='mode',
            field=models.CharField(default='', max_length=32),
        ),
    ]
