# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171218_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='phrase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Phrase'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='phrase',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='translation',
            name='phrase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Phrase'),
        ),
    ]
