# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_answer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='answer',
            name='correction',
            field=models.BooleanField(default=False),
        ),
    ]
