# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171218_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('total_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('answer', models.ManyToManyField(to='api.Answer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
