# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsession',
            old_name='answer',
            new_name='answers',
        ),
    ]
